name = "SymGroupRepresentations"
uuid = "012f8b28-f87f-4a0e-ba3f-b2c050e084d0"
authors = ["Zhengyuan Yue <yuezy1997@icloud.com>", "Lukas Devos"]
version = "0.0.1-DEV"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TensorKitSectors = "13a9c161-d5da-41f0-bcbd-e1a08ae0647f"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[compat]
AbstractAlgebra = "0.44.8"
Combinatorics = "1"
LinearAlgebra = "1"
TensorKit = "0.14"
TensorKitSectors = "0.1.2"
TensorOperations = "5.1.4"
julia = "1.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestExtras = "5ed8adda-3752-4e41-b88a-e8b09835ee3a"

[targets]
test = ["Test", "TestExtras", "TensorKit", "Combinatorics", "Aqua", "Random"]
